### ISSUE TITLE
@mdx-js_react.js does not provide an export named 'mdx' [Bug] 

### ISSUE THREAD

**Issue by adamSneller** [storybookjs/builder-vite#398]
### What version of `vite` are you using?

2.9.9

### System info and storybook versions

Environment Info:

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 3.2.0 - /usr/local/bin/yarn
    npm: 8.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Edge: 101.0.1210.53
    Firefox: 97.0.1
    Safari: 13.1.2
NPM Packages

"dependencies": {
    "vue": "^3.2.25"
  },
  "devDependencies": {
    "@babel/core": "^7.18.2",
    "@mdx-js/react": "^2.1.1",
    "@storybook/addon-actions": "^6.5.6",
    "@storybook/addon-essentials": "^6.5.6",
    "@storybook/addon-interactions": "^6.5.6",
    "@storybook/addon-links": "^6.5.6",
    "@storybook/addon-postcss": "^2.0.0",
    "@storybook/builder-vite": "^0.1.35",
    "@storybook/testing-library": "^0.0.11",
    "@storybook/vue3": "^6.5.6",
    "@tailwindcss/forms": "^0.5.2",
    "@vitejs/plugin-vue": "^2.3.3",
    "autoprefixer": "^10.4.7",
    "babel-loader": "^8.2.5",
    "postcss": "^8.4.14",
    "tailwindcss": "^3.0.24",
    "vite": "^2.9.9",
    "vue-loader": "^16.8.3"
  }

### Describe the Bug

MDX files throw the following error in Storybook:

    SyntaxError: The requested module '/node_modules/.vite-storybook/deps/@mdx-js_react.js?v=4345b16f' does not provide an export named 'mdx'

I am using Storybook inside an NPM workspace / Monorepo. If I install Storybook into a fresh project (outside the monorepo) I do not have this issue.

Any ideas?

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by IanVS** [comment]
This looks similar to https://github.com/storybookjs/builder-vite/issues/391.  Are you using react 18, either in that package of your monorepo or another one in the monorepo?

**Comment by adamSneller** [comment]
Hi @IanVS - Thanks for addressing this! Other than as a dependency of Storybook(?) I'm not using React anywhere. Everything I build is in Vue3.

**Comment by IanVS** [comment]
Interesting.  I think you can work around this for now with `npm i --save-dev @mdx-js/react@1 --force`.

**Comment by adamSneller** [comment]
Well, that got rid of the error message! But now when I load `Introduction.stories.mdx` I just get a blank page.

When I check the console, I see these errors:

    Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17.

    Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
    1. You might have mismatching versions of React and the renderer (such as React DOM)
    2. You might be breaking the Rules of Hooks
    3. You might have more than one copy of React in the same app

    VM692 chunk-B4F5F2LW.js:13389 The above error occurred in the 
    <MDXCreateElement> component:

    at http://localhost:6006/node_modules/.vite-storybook/deps/@mdx-js_react.js?v=38219663:139:30
    at MDXContent (http://localhost:6006/src/stories/Introduction.stories.mdx?import:17:3)
    at AddContext2 (http://localhost:6006/node_modules/.vite-storybook/deps/chunk-NSXUMJUF.js?v=38219663:1504:24)
    at page
    at div
    at http://localhost:6006/node_modules/.vite-storybook/deps/chunk-EIWNNGFT.js?v=38219663:1816:45
    at div
    at http://localhost:6006/node_modules/.vite-storybook/deps/chunk-EIWNNGFT.js?v=38219663:1816:45
    at MDXProvider2 (http://localhost:6006/node_modules/.vite-storybook/deps/chunk-NSXUMJUF.js?v=38219663:252:46)
    at ThemeProvider2 (http://localhost:6006/node_modules/.vite-storybook/deps/chunk-EIWNNGFT.js?v=38219663:1863:44)
    at SourceContainer2 (http://localhost:6006/node_modules/.vite-storybook/deps/chunk-NSXUMJUF.js?v=38219663:991:23)
    at DocsContainer2 (http://localhost:6006/node_modules/.vite-storybook/deps/chunk-NSXUMJUF.js?v=38219663:1798:22)

**Comment by IanVS** [comment]
That part is normal, it's because react 17 is still used to generate the docs pages.  

Can you provide a reproduction that we can look into?  Otherwise, it's difficult to help troubleshoot.

**Comment by IanVS** [comment]
@adamSneller sorry, that suggestion was for @l4dybird.  I took a look at your reproduction (thanks for providing it), and I got it working by explicitly installing react@17.  This _shouldn't_ have to be necessary, and hopefully you'll be able to remove it once we get MDX all sorted out.  I pushed up two commits to the main branch of your repo.

**Comment by adamSneller** [comment]
Wow, that did it! Thanks @IanVS - that's fantastic!

**Comment by hsheikhali1** [comment]
Sorry to reopen this issue but I'm getting this error and I'm using react v17 in my pnpm monorepo.. I can't get mdx to work with storybook...

**Comment by SSTPIERRE2** [comment]
> Interesting. I think you can work around this for now with `npm i --save-dev @mdx-js/react@1 --force`.

@IanVS my hero! I'm in the middle of upgrading a React/Storybook/Vite project to React 18, ran into this exact issue where mdx stories wouldn't load due to the error and your suggestion to install 1.x of mdx-js/react worked! Also this quote

> That part is normal, it's because react 17 is still used to generate the docs pages.

So glad I found this GH issue, because I was confused why I was still seeing that message in the console and thought the upgrade didn't work 😇

**Comment by techpeace** [comment]
I'm also on React 18 w/vite, and I was able to get up and running with `npm i --save-dev @mdx-js/react@1 --force` (actually `pnpm`, in my case).

**Comment by IanVS** [comment]
@techpeace the other thing you can try is to use mdx2, which actually is made for react 18.  https://gist.github.com/shilman/6ff2d7e18db8846e8fc552fb432ae4f6. I wonder if that would also solve the issue for you.

**Comment by techpeace** [comment]
Thanks, @IanVS!

Running through those instructions, `"@storybook/react": "^7.0.0-alpha.28"` throws the following:

`Package subpath './preset' is not defined by "exports" in [REDACTED]/@storybook/react/package.json`

This may have something to do with my using pnpm (though that subpath is indeed not defined).

Not a huge deal, since I got it running with the 1.x branch, for the moment.

**Comment by IanVS** [comment]
You shouldn't need to use `@storybook/react` directly anymore, it's now `@storybook/react-vite`.  If the migration didn't run, you can try `npx sb@future automigrate`, or follow the manual instructions in https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#framework-field-mandatory
